version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - nastya
  # в видео было сказано, что вместо php можно поставить любое другое название
  # ну вот)
  nastya:
    image: php:8.3-fpm
    volumes:
      - ./code:/code